# backend/src/main/resources/application.yml

spring:
  application:
    name: moms-kitchen

  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:moms_kitchen}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: ${DB_USERNAME:root}
    # Default to no password for local dev unless overridden via DB_PASSWORD
    password: ${DB_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none                 # use schema.sql/data.sql instead
    open-in-view: false
    show-sql: true                   # dev-friendly; disable in prod
    properties:
      hibernate:
        format_sql: true
        jdbc.time_zone: UTC

  sql:
    init:
      mode: always                   # run schema.sql and data.sql on startup
      continue-on-error: true        # safe if tables already exist

server:
  port: ${SERVER_PORT:8080}
  forward-headers-strategy: framework

# Development-friendly pickup settings
pickup:
  # Set to your local zone so pickupTime is interpreted locally
  zoneId: ${PICKUP_ZONE_ID:America/New_York}
  # Relax minimum future minutes for easier local testing
  requireFutureMinutes: ${PICKUP_REQUIRE_FUTURE_MINUTES:0}
  # Loosen strict day match so you don't have to align day-of-week during testing
  strictDayMatch: ${PICKUP_STRICT_DAY_MATCH:false}

# Minimal log config (turn down SQL noise by switching to INFO in prod)
logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG         # show SQL (dev)
    org.hibernate.orm.jdbc.bind: TRACE  # show SQL params (dev)

# Simple, externalized CORS config your CorsConfig.java can bind to
cors:
  allowed-origins: "http://localhost:5173,http://localhost:3000"
  allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
  allowed-headers: "*"
  allow-credentials: true

# Admin API key for /api/admin/** filter
admin:
  apiKey: ${ADMIN_API_KEY:changeme}

# --- Optional profile-specific overrides ---
---
spring:
  config:
    activate:
      on-profile: prod
  jpa:
    show-sql: false
logging:
  level:
    org.hibernate.SQL: INFO
    org.hibernate.orm.jdbc.bind: INFO
cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:https://your-frontend.example.com}

# Pricing configuration
pricing:
  taxRate: 0.00   # disable tax entirely (0%)
